### PR TITLE
Rudimentary fix for the table view on small screen

### PR DESCRIPTION
**Pull request by zl8244**

### CODE REVIEW

**Review by saltyypanda — COMMENTED** [review]
Can you give more context on what this does to what's already on the website?

**Comment by zl8244** [comment]
The table on the About/Consitution page ends up formatting incorrectly when in mobile view. This change makes it so that the Constitution is readable, even if the table becomes less wieldy.

Before:
Before

After:
After

**Comment by zl8244** [comment]
If someone could figure out a way to get the table to format correctly without the need for each table cell to be a scrollable box, then I welcome it.

**Comment by saltyypanda** [comment]
Oh that's great! Thank you for doing that!

**Pull request merged**
