### PR TITLE
Dev/darkmode navbar

### PR DESCRIPTION
**Pull request by AriasLcr**
Moved the darkmode button to the top nav bar.
image

Get involved buttons at teh bottom removed.
image

### CODE REVIEW

**Comment by saltyypanda** [comment]
Design does not approve of these changes :( is there a way to make the theme toggle button still in the bottom left corner, but fixed in place?

**Comment by AriasLcr** [comment]
Reverted the changes for the Darkmode Toggle. UI Team decided for it to stay on the bottom.

chrome_AQtfuCbDZY

**Comment by stretchyDawg** [comment]
It looks like that's not in place, based on Tess' request, it should be sticky at the bottom left? It'll be similar to the scroll up button designed by Zhiwei right now. We can talk about it next Sunday.

**Comment by AriasLcr** [comment]
The darkmode button is now fixed to the bottom left of the display

https://github.com/rit-sse/WebsiteTheSSEquel/assets/102717383/f005a076-fb0d-4fcb-9204-eba617f7576d

**Review by saltyypanda — APPROVED** [review]

**Pull request merged**
